### ISSUE TITLE
AuthFunc(ProtectedHandler") typo in README

### ISSUE THREAD

**Issue by alexellis** [mrtobe/bago#1]
I think this should be `AuthFunc(ProtectedHandler)`

**Comment by mrtobe** [comment]
Hello @alexellis 

thanks for reporting. I resolved the typo.

Best
Tobias

**Comment by alexellis** [comment]
Are you going to be supporting htaccess files etc?

**Comment by mrtobe** [comment]
Not yet planned - but htaccess file support would be something after v1.0.0.
I will add that to the milestones list.
